### ISSUE TITLE
cannot handle import map in other deno package

### ISSUE THREAD

**Issue by podhmo** [podhmo/deno-bundle#2]
e.g.

```console
$ deno run -A main.ts ../with-help/mod.ts
error: Uncaught (in promise) Error: Unable to output during bundling: load_transformed failed: failed to analyze module: failed to resolve @std/cli/parse-args from file:///home/po/ghq/github.com/podhmo/with-help/parse-args.ts: Cannot resolve "@std/cli/parse-args" from "file:///home/po/ghq/github.com/podhmo/with-help/parse-args.ts".
      const ret = new Error(getStringFromWasm0(arg0, arg1));
                  ^
    at __wbg_new_28c511d9baebfa89 (https://jsr.io/@deno/emit/0.46.0/emit.generated.js:557:19)
    at <anonymous> (wasm://wasm/010a1b62:1:3287273)
    at <anonymous> (wasm://wasm/010a1b62:1:429097)
    at <anonymous> (wasm://wasm/010a1b62:1:1820413)
    at <anonymous> (wasm://wasm/010a1b62:1:2928941)
    at __wbg_adapter_46 (https://jsr.io/@deno/emit/0.46.0/emit.generated.js:247:6)
    at real (https://jsr.io/@deno/emit/0.46.0/emit.generated.js:231:14)
    at ext:core/01_core.js:291:9
    at eventLoopTick (ext:core/01_core.js:175:7)
```

**Comment by podhmo** [comment]
fixed by #7
